module.exports.categorySchema = require("./category.model")
module.exports.subcategorySchema = require("./subcategory.model")
module.exports.productSchema = require("./product.model")
module.exports.userSchema = require("./user.model")
module.exports.cartSchema = require("./cart.model")