module.exports.categoryService = require("./category.service")
module.exports.subcategoryService = require("./subcategory.service")
module.exports.productService = require("./product.service")
module.exports.userService = require("./user.service")
module.exports.cartService = require("./cart.service")